### ISSUE TITLE
Events not ingested when run as a plug-in app under Docker

### ISSUE THREAD

**Issue by nblumhardt** [datalust/sqelf#28]
The plug-in app should support Docker in theory (we include Linux binaries), but even with the GELF port mapped, events aren't currently ingested. Needs investigation. (Under Docker, using `datalust/sqelf` is recommended anyway, so this is not a critical issue.)

**Comment by nblumhardt** [comment]
(This might end up requiring a port mapping in the Dockerfile, so may be "as designed").

**Comment by KodrAus** [comment]
I think the subtelty here is how Docker wants you to map udp ports:

```
-p 12201:12201/udp
```

I gave this a test as a Seq app and it did seem to work out ok when the ports were opened, so I'll go ahead and close this one now.
