### ISSUE TITLE
Conditionally log diagnostic output

### ISSUE THREAD

**Issue by nblumhardt** [datalust/sqelf#30]
Currently the app outputs a "Termination signal received..." event every time it's shut down, which ends up as noise in the Seq log stream. We could enable this only on receiving `--verbose` or similar on the command-line?

**Comment by KodrAus** [comment]
We use environment variables for other bits of configuration, so we could do the same here?

Otherwise it might be time to bring in `clap` so we can read configuration from args as well as variables.
