### ISSUE TITLE
Consider cleaning up expired chunked msgs for every N unchunked msgs

### ISSUE THREAD

**Issue by KodrAus** [datalust/sqelf#35]
Right now, we only check for expired message chunks when processing message chunks. That means it's possible unprocessed, expired chunks could be sitting around for a very long time if the server is mostly working with unchunked messages.

We could use a simple wrapping counter and clean up expired chunks after every 1000 or so unchunked messages received.

**Comment by nblumhardt** [comment]
An alternative way of looking at this is that the cost is only paid for expired-chunk eviction if chunking is being used - which makes the current design a pretty good pay-for-play setup, would you agree?

**Comment by KodrAus** [comment]
That was the original intention. I'm trying to think of ways an antagonistic actor could try force the server into a degenerate state, but after thinking about it more, the current behaviour does seem ok to me.
