### ISSUE TITLE
Error has Level(err) in seq

### ISSUE THREAD

**Issue by devployment** [datalust/sqelf#37]
Error logs, originating from PHP, appear in Seq as `Level (err)`

![image](https://user-images.githubusercontent.com/7137845/52498208-6fcac200-2bd8-11e9-921b-00e434361daf.png)

By that, they are missing the red dot, and the red background as compared with .NET logs.

Here they have `Level (error)`.

![image](https://user-images.githubusercontent.com/7137845/52498272-9d177000-2bd8-11e9-9f32-b8c1383c55a9.png)

Not sure if this is something that needs tweaking in the log producer or Sqelf.

I cannot proof it, but I'm fairly sure that the behavior was different in an older Sqelf version, receiving the same logs.

Currently running

Seq: `5.0.2562`
Sqelf: `sqelf:latest`

**Comment by nblumhardt** [comment]
Thanks @devployment - this one is a Seq issue (I think `sqelf` did originally try mapping GELF levels in the early versions), but we should just recognize these in the Seq UI.

I've raised:https://github.com/datalust/seq-tickets/issues/797 to track it, which should fit into the upcoming Seq 5.1.

Cheers!

**Comment by kjetim** [comment]
Was this solved?  I still get this behavour and I am using SEQ 2024.3.11510 and GELF app version 3.0.458.

**Comment by nblumhardt** [comment]
Hi @kjetim; yes, it's likely any new occurrence of this is either a regression or a new issue. Raising a ticket on `datalust/seq-tickets` with the details will help get it sorted out. Thanks!
