### ISSUE TITLE
Add TCP support

### ISSUE THREAD

**Issue by KodrAus** [datalust/sqelf#48]
Related to #43 

We've had some reports of instability in Windows environments. At some point over time, we seem to lose our UDP socket, and will block indefinitely in `GetQueuedCompletionStatusEx` deep down in `mio`'s IOCP translation layer. No more events will be logged unless the process is recycled.

After very thoroughly reviewing our side of things, it doesn't _look_ like we're triggering a shutdown that closes the socket but blocks before the process can exit.

The version of `mio` that we're using via `tokio` isn't the latest one, so it's possible there's been some changes somewhere in that stack.

It's also possible UDP sockets on Windows just haven't received a lot of attention yet in `mio`/`tokio`, so we'd like to implement an alternative TCP-based GELF server that can be used when running as a Seq app on Windows.

Now that we have a better integration test harness we can also make sure various chunking scenarios don't cause the server to block.

In the meantime, folks that are affected by this can try using the `sqelf` Linux Docker container.

**Comment by nblumhardt** [comment]
I think this should probably just be titled "Add TCP support", as #43 captures the stability issue on Windows that we're addressing with this. Thoughts?

**Comment by KodrAus** [comment]
Users can enable TCP support instead of UDP in the following ways:

- For the Seq input: change the _GELF address_ property of your app instance to start with `tcp://`.
- For the Docker container: change the `GELF_ADDRESS` environment variable to start with `tcp://`.

**Comment by KodrAus** [comment]
We've had TCP support out inn the wild now for a few months so I'll go ahead and close this one. We can open new issues for anything new that comes up.
