### ISSUE TITLE
Add TLS Support

### ISSUE THREAD

**Issue by KodrAus** [datalust/sqelf#68]
For the TCP transport, we should look at supporting TLS. As a starting point, there are [TLS APIs for `tokio`](https://github.com/tokio-rs/tls), which is the async runtime this server uses.

**Comment by luscit** [comment]
Anything happened here related to TLS? Currently we are looking into the topic of getting GELF formatted messages (from php) to Seq.

**Comment by nblumhardt** [comment]
Thanks for the ping, @luscit. No, unfortunately, we haven't made any progress on this recently. We're keen to push this forward, but won't be able to schedule work here before the 2021.3 release makes it out the door (currently late October).

(If anyone following along is interested in sketching up a proposal or sending a PR before then, it would be most welcome.)

**Comment by rjhenry** [comment]
A few months on, has there been any movement on this? We're in a very similar situation to Luscit where we need to transmit GELF from a k8s cluster (in AKS) to Seq (on-prem) and would rather avoid plaintext-sending all of that traffic.

**Comment by nblumhardt** [comment]
Thanks for the ping @rjhenry. No movement yet, but seems like we should start assembling a plan.

Getting a certificate into `sqelf` is the first problem to deal with, I think. Are you running it as an input (`Seq.Input.Gelf`), or as a container (`datalust/sqelf`)?

**Comment by rjhenry** [comment]
We're running as a container, so can trivially mount in certificate files.

**Comment by nblumhardt** [comment]
👍 thanks for your reply. Thinking about this some more, if `sqelf` accepted a certificate file path, and an (optional) certificate file password through regular app settings, this should work in both the app and container deployment configurations.

We'll aim to loop back around to this as soon as possible.
