### ISSUE TITLE
GELF processing failed

### ISSUE THREAD

**Issue by Mattes83** [datalust/sqelf#80]
Hi!

I am running Seq with gelf plugin in a kubernetes environment.
Logs are shipped by fluent-bit.
Most log messages appear correctly in Seq, but some messages cannot be parsed correctly. Sometimes I get the error "GELF processing failed" and in the details I can see "expected `,` or `}` at line 1 column 1392". So I guess fluent-bit is sending some wrongly formatted data to sqelf. 
The issue is that its very hard to find out which log is not sent correctly, because it is not included in the error message. So I am not able to find out where the error comes from. Is there a chance to see message that cant be parsed or do you have any other hint on how to debug this?

Best regards

**Comment by nblumhardt** [comment]
Hi @Mattes83, thanks for getting in touch.

Do you have the "enable diagnostics" checkbox in the GELF input's settings page checked? I believe this will cause more information to be written when message parsing fails. (You can then see these messages by clicking the number with the zigzag arrow icon next to the input's name in the Settings > Apps screen.)

If you're running the input as a `datalust/squelf` Docker container instance, you can alternatively set `GELF_ENABLE_DIAGNOSTICS=True` in its environment.

Let me know if this helps,
Nick

**Comment by Mattes83** [comment]
Hi Nick,

thanks for the hint where to find the diagnostic logs.
When using the docker version Seq does not list Sqelf Input under Settings -> Apps. I am not sure if this is a known quirk?!
In my case I could easily circumvent this by installing the GELF plugin via Seq's web ui and deactivating the sidecar container.

**Comment by nblumhardt** [comment]
Great, thanks for the follow-up, @Mattes83 👍

**Comment by Mattes83** [comment]
Hi again,

I guess I closed this issue too early. I was able to enable the diagnostics, but there is still no information about the original message that could not be processed.

![image](https://user-images.githubusercontent.com/22005222/99216625-5fe10880-27d6-11eb-916f-8416d16102e2.png)

Do you have any idea how to track this down? 

Best Regards

**Comment by nblumhardt** [comment]
Hi @Mattes83 - we'll put our heads together and let you know what we come up with. It might require enhancing the diagnostic, which is produced in: https://github.com/datalust/sqelf/blob/dev/sqelf/src/server/mod.rs#L210

**Comment by KodrAus** [comment]
It looks like we only include the raw payload (what was originally sent by the GELF logger) on events that were parsed and processed correctly.

I'll improve our diagnostics a bit here by replacing our current error handling with [`anyhow`](https://docs.rs/anyhow/1.0.34/anyhow/) so that we can include a portion of a payload that couldn't be parsed if we hit one. That might make it easier for you to track down where it's coming from.

**Comment by KodrAus** [comment]
Hi @Mattes83 We've published a new version of the package and container (as version `2.0.298`) that includes a fragment of the invalid payload when it can't be parsed. If you update your Seq app and keep the extended diagnostics enabled you should get some more details about the event that couldn't be parsed.

**Comment by Mattes83** [comment]
Thats great news. I will try it with the updated version, thanks for the enhancement
