### ISSUE TITLE
ARM64 container for seq-input-gelf

### ISSUE THREAD

**Issue by jimmcslim** [datalust/sqelf#94]
A `seq-input-gelf` container that supports the ARM architecture would be great, to run within a `Minikube` environment on an M1 Mac.

**Comment by nblumhardt** [comment]
Thanks for the suggestion 👍

**Comment by KodrAus** [comment]
This would be great to do. We need to get https://github.com/datalust/seqcli/issues/227 sorted first.

**Comment by jimmcslim** [comment]
Awesome. I'm trying to replicate the k8s -> fluent-bit -> seq-input-gelf -> seq story on my local machine but not having much luck with k8s logs pumping through, trying to establish if its is something in the 'best effort' x86 emulation that Docker Desktop does via QEMU that is getting in the way.

**Comment by KodrAus** [comment]
Ah that sounds... Fun 🙃 Unfortunately there are a lot of moving parts in that story so it's hard to point the finger at any one piece.

**Comment by KodrAus** [comment]
Just an update on this one, we've done some work in https://github.com/datalust/seqcli/pull/228 to produce ARM-based containers for `seqcli`. Once we've got those published we'll be able to start using them as base images for the GELF input here too.

**Comment by KodrAus** [comment]
Thanks for your patience on this one @jimmcslim! I've opened #99 to finish off ARM support for the GELF input here. It's probably far too late for your original need but should now make it possible to run the GELF input on M1-based dev machines or Graviton.

**Comment by KodrAus** [comment]
As of `datalust/seq-input-gelf:2.0.343` we have an ARM build of the container available.
