### ISSUE TITLE
Question: Regex transformation of message possible?

### ISSUE THREAD

**Issue by Ergamon** [datalust/sqelf#98]
Hello,

Maybe I am doing something wrong, but I made my first steps with the seq-input-gelf container. Everything works like a charm and probably as expected.

The seq-input-gelf container forwards to the seq instance and my test container logs to the gelf container.

But the message feels a little ugly.

My first attempt I did make with a traefik container. The message shown in Seq is the same one I get from docker logs:

```
time="2022-04-03T19:10:20Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"
```

So that is indeed the message traefik writes to the log. But as the information about time and log level is already there i would like to transform the message to

```
Starting provider *acme.ChallengeTLSALPN
```

Is there any good way to achieve this?

**Comment by KodrAus** [comment]
Hi @Ergamon :wave:


We actually don't have a nice way to do this currently. Seq's CLI has this concept of [extraction patterns](https://github.com/datalust/seqcli#extraction-patterns) that would be a good fit for this. We don't have a Rust implementation of them yet but I think this sounds like a great addition.

**Comment by Ergamon** [comment]
Thanks for your quick reply. At least I now know that I have not overlooked something ;)

Intitially I had thought about some regex replace mechanism, but what you showed is also fine.

As every container has its own "logging syntax" it cannot be something hard wired in the gelf server.

If I could wish for this new feature, my idea would be to have some label on the container for the extraction pattern.
So server side I would configure the name of the label for the pattern, which is then not send to the seq.
On the container side I would have to add the label and add the label to the logging options for gelf.

**Comment by KodrAus** [comment]
Coming back to this, the way you could do this today would be through something like fluentbit, which lets you transform and reshape your logs between their producer and the eventual consumer. In the future we might consider some similar data pipelining functionality in Seq itself, but don't have any immediate plans for it.

This would be great to support, but having thought about it I think we should avoid accumulating these sorts of configurable transformations in the GELF input itself.

Thanks again for the suggestion @Ergamon!
